### PR TITLE
[MRG + 1] FIX fixed fold file init logic

### PR DESCRIPTION
**Pull request by kowey**
Need to copy the fixed fold file over

### CODE REVIEW

**Comment by moreymat** [comment]
Is `create_folds` called anywhere? I can't find any occurrence of this.

**Comment by kowey** [comment]
I think it's in the the new attelo.harness shared logic somewhere.
Sorry btw, have been impulsively merging things in left and right.

**Comment by moreymat** [comment]
Is this still active or ready to merge?

**Comment by kowey** [comment]
I think it's ready and I just forgot it existed.

**Pull request merged**
